# Generated by Django 4.1.3 on 2022-11-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
